# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: myrachane.emtypyie-cli
PackageVersion: 2.5.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: emtypyie.exe
    PortableCommandAlias: emtypyie
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/myrachane/emtypyie-cli/releases/download/v2.5.0/emtypyie-cli-native-windows-x64-2.5.0.zip
    InstallerSha256: 9548F80E95DAB147EF5734938F5CCC2ABD9762AD9B4C84A9A4E7CC3246906424
ManifestType: installer
ManifestVersion: 1.6.0
